import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { Theme } from "@utils/providers/framework";
import Alert from "@utils/providers/alert";
import Navbar from "@components/navbar";

import "@css/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-mui-color-scheme="dark">
      <body className={inter.className}>
        <Theme>
          <Alert>
            <Navbar />
            {children}
          </Alert>
        </Theme>
      </body >
    </html >
  );
}
