import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Alert from "@/utils/providers/alert";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Alert>
          {children}
        </Alert>
      </body>
    </html>
  );
}
